import { FontFamilyId } from './types';
export const NOTE_FONTS: {id:FontFamilyId; name:string; family:string}[] = [
  {id:'sans',name:'系统默认',family:'system-ui, "Microsoft YaHei", sans-serif'},
  {id:'serif',name:'宋体',family:'SimSun, serif'},
  {id:'kai',name:'楷体 · 手写',family:'KaiTi, STKaiti, serif'},
  {id:'mashanzheng',name:'马善政 · 毛笔手写',family:'"Ma Shan Zheng", KaiTi, cursive'},
  {id:'longcang',name:'龙藏 · 随性手写',family:'"Long Cang", KaiTi, cursive'},
  {id:'zhimangxing',name:'志莽行 · 潇洒手写',family:'"Zhi Mang Xing", KaiTi, cursive'},
  {id:'zcool',name:'站酷快乐 · 圆润手写',family:'"ZCOOL KuaiLe", sans-serif'},
  {"id":"jason1","name":"清松1 · 圆润","family":"\"JasonHandwriting1\", KaiTi, serif"},
  {"id":"jason2","name":"清松2 · 秀气","family":"\"JasonHandwriting2\", KaiTi, serif"},
  {"id":"jason3","name":"清松3 · 呆萌","family":"\"JasonHandwriting3\", KaiTi, serif"},
  {"id":"jason4","name":"清松4 · POP","family":"\"JasonHandwriting4\", KaiTi, serif"},
  {"id":"jason5","name":"清松5 · 行楷","family":"\"JasonHandwriting5\", KaiTi, serif"},
  {"id":"jason6","name":"清松6 · Q萌","family":"\"JasonHandwriting6\", KaiTi, serif"},
  {"id":"jason7","name":"清松7 · 飘逸","family":"\"JasonHandwriting7\", KaiTi, serif"},
  {"id":"jason8","name":"清松8 · 随性","family":"\"JasonHandwriting8\", KaiTi, serif"},
  {"id":"jason9","name":"清松9 · 文青","family":"\"JasonHandwriting9\", KaiTi, serif"},
  {"id":"liujianmaocao","name":"刘建毛草 · 草书","family":"\"Liu Jian Mao Cao\", KaiTi, cursive"},
  {"id":"xiaowei","name":"站酷小薇 · 文艺宋体","family":"\"ZCOOL XiaoWei\", SimSun, serif"},
  {"id":"qingke","name":"站酷庆科黄油 · 标题体","family":"\"ZCOOL QingKe HuangYou\", sans-serif"},
  {"id":"fangsong","name":"仿宋 · 文稿","family":"FangSong, STFangsong, serif"},
  {"id":"dengxian","name":"等线 · 简洁","family":"DengXian, \"Microsoft YaHei\", sans-serif"},
  {"id":"jhenghei","name":"微软正黑 · 清晰","family":"\"Microsoft JhengHei\", \"Microsoft YaHei\", sans-serif"},
  {id:'mono',name:'等宽（原有）',family:'Consolas, monospace'},
  {id:'rounded',name:'圆体（原有）',family:'"Microsoft YaHei", sans-serif'},
];
